services:
  db:
    image: postgres:16
    container_name: feedback_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
    ports:
      - "5432:5432"
    volumes:
      - feedback_db_data:/var/lib/postgresql/data
volumes:
  feedback_db_data:
